In [5]:
import torch

# Part 1
def activation(x):
    return 1/(1+torch.exp(-x))


torch.manual_seed(7)

features = torch.randn((1, 5))
weights = torch.randn_like(features)
bias = torch.randn((1, 1))


# ------------------------------EJERCICIO------------------------------------
## Calculate the output of this network using the weights and bias tensors

FirstOutput = activation(torch.sum(features * weights) + bias)

## Calculate the output of this network using matrix multiplication
MatrixOutput = activation(torch.matmul(features,weights.view(5, 1)) + bias)

#---------------------------------------------------------------------------
print(FirstOutput)
print(MatrixOutput)

tensor([[0.1595]])
tensor([[0.1595]])


In [3]:
import torch
import numpy as np

def activation(x):
    return 1/(1+torch.exp(-x))
    
torch.manual_seed(7)
features = torch.randn((1, 3))
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))


# ------------------------------EJERCICIO------------------------------------
## Calculate the output for this multi-layer network
fInput = activation(torch.matmul(features,W1) + B1)
MultiOutput = activation(torch.matmul(fInput,W2) + B2)
print(MultiOutput)
#---------------------------------------------------------------------------

tensor([[0.3171]])


In [7]:
import numpy as np
import torch

np.set_printoptions(precision=8)
a = np.random.rand(4,3)
print(f"El primer arreglo de numpy: \n {a}")

torch.set_printoptions(precision=8)
b = torch.from_numpy(a)
print(f"\n El arreglo de numpy en tensores de pytorch: \n {b}")

b.numpy()

# Cualquier operacion hecha desde un lado, cambia los dos lados
b.mul_(2)

print(f"\n El arreglo de numpy despues de hacer una ejecucion en el tensor: \n {a}")

El primer arreglo de numpy: 
 [[0.38954418 0.04062172 0.51469841]
 [0.21418428 0.73011719 0.55723592]
 [0.73010027 0.37578019 0.51620522]
 [0.66900494 0.36942506 0.26744215]]

 El arreglo de numpy en tensores de pytorch: 
 tensor([[0.38954418, 0.04062172, 0.51469841],
        [0.21418428, 0.73011719, 0.55723592],
        [0.73010027, 0.37578019, 0.51620522],
        [0.66900494, 0.36942506, 0.26744215]], dtype=torch.float64)

 El arreglo de numpy despues de hacer una ejecucion en el tensor: 
 [[0.77908836 0.08124344 1.02939681]
 [0.42836856 1.46023437 1.11447184]
 [1.46020055 0.75156038 1.03241043]
 [1.33800988 0.73885012 0.5348843 ]]
